%% ============================================================
%  STEP 3: 3-D SOLID OF REVOLUTION  [Generated by Parameter Studio]
%  ============================================================
clear; clc; close all;

input_mat_file  = 'lens_data_gradual_N2003_test.mat';
output_xyz_file = 'lens_revolved_xyz.txt';
n_theta         = 120;

%% ---------- Load 2-D lens geometry ----------
S = load(input_mat_file);
if ~isfield(S,'final_lens')
    error('lens_data.mat must contain variable "final_lens".');
end
final_lens   = S.final_lens;
layers_count = isfield(S,'layers_count')*S.layers_count + ...
               ~isfield(S,'layers_count')*numel(final_lens);
src = isfield(S,'source_pos')*S.source_pos(:).' + ...
      ~isfield(S,'source_pos')*[0 0];
src_x = src(1); src_y = src(2); src_z = 0;

%% ---------- Figure & axes ----------
figure(1);
set(gcf, 'Color', 'w', 'Units','pixels', 'Position',[100 100 1000 780]);
ax = axes('Color', 'w', ...
          'XColor','k','YColor','k','ZColor','k', ...
          'GridColor',[0.6 0.6 0.6],'GridAlpha',0.5, ...
          'FontSize',12,'FontName','Helvetica','LineWidth',1.2);
hold(ax,'on'); axis equal; grid on;

view(25, 18);
ax.CameraViewAngle = 6;

xlabel('X (mm)','Color','k','FontSize',13,'FontWeight','bold');
ylabel('Y (mm)','Color','k','FontSize',13,'FontWeight','bold');
zlabel('Z (mm)','Color','k','FontSize',13,'FontWeight','bold');
title('3D Lens Geometry — Solid of Revolution', ...
      'Color','k','FontSize',15,'FontWeight','bold');

%% ---------- Colormap ----------
cmap = bone(layers_count);
colormap(ax, cmap);
cb = colorbar(ax);
cb.Color = 'k';
cb.Label.String  = 'Refractive Index Layer (inner → outer)';
cb.Label.Color   = 'k';
cb.Label.FontSize = 12;
clim([1 layers_count]);

%% ---------- Source marker ----------
plot3(src_x, src_y, src_z, 'p', ...
      'MarkerFaceColor',[0.85 0.1 0.1], ...
      'MarkerEdgeColor','k', ...
      'MarkerSize', 14, 'LineWidth', 1.2);
text(src_x, src_y, src_z + 8, 'Source', ...
     'Color','k','FontSize',10,'FontWeight','bold');

%% ---------- 3-D solid of revolution ----------
theta = linspace(0, 2*pi, n_theta);

for j = 1:layers_count
    curve = final_lens{j};
    if isempty(curve), continue; end
    curve = curve(curve(:,2) >= 0, :);
    if isempty(curve), continue; end

    x = curve(:,1);
    r = curve(:,2);
    [T, Xgrid] = meshgrid(theta, x);
    R   = repmat(r, 1, n_theta);
    Y   =  R .* cos(T);
    Z   =  R .* sin(T);
    C   = ones(size(Xgrid)) * j;

    alpha_val = 0.55;

    surf(Xgrid, Y, Z, C, ...
        'FaceAlpha',  alpha_val, ...
        'FaceColor',  'flat', ...
        'EdgeColor',  'none', ...
        'AmbientStrength',  0.35, ...
        'DiffuseStrength',  0.75, ...
        'SpecularStrength', 0.45, ...
        'SpecularExponent', 20);
end

%% ---------- Lighting ----------
delete(findall(gcf,'Type','light'));
l1 = light('Position',[ 200  150  200],'Style','infinite','Color',[1   1   1  ]);
l2 = light('Position',[-100 -100 -100],'Style','infinite','Color',[0.3 0.3 0.5]);
lighting gouraud;
material([0.35 0.75 0.45 20 0.3]);

ax.TickDir = 'out';
ax.Box = 'off';
fprintf('Done.\n');